Action:
#攻擊顯示傷害(向上)
#Attack display damage (up)
- Action[a=AttackDisplayUp] ~onAttack

#攻擊顯示傷害(向上)(爆擊)
#Attack display damage (up)(Critical)
- Action[a=AttackCritDisplayUp] ~onCrit

#攻擊顯示傷害(拋出)
#Attack display damage (throw)
#- Action[a=AttackDisplayThrow] ~onAttack

#攻擊怪物顯示血量
#Attacking monsters shows blood volume.
- Action[a=EntityTopDisplayMonster;mark={target_uuid}EntityTopDisplayMonster] ~onAttack
- Action[a=EntityTopDisplayMonster;mark={target_uuid}EntityTopDisplayMonster] ~onCrit
- Action[mark={target_uuid}EntityTopDisplayMonster;stop=true] ~onDeath

#攻擊動物顯示血量
#Attack animals show blood volume.
- Action[a=EntityTopDisplayAnimal;mark={target_uuid}EntityTopDisplayAnimal] ~onAttack
- Action[a=EntityTopDisplayAnimal;mark={target_uuid}EntityTopDisplayAnimal] ~onCrit
- Action[mark={target_uuid}EntityTopDisplayAnimal;stop=true] ~onDeath

#攻擊玩家顯示資訊
#The attacking player displays information.
- Action[a=EntityTopDisplayPlayer;mark={target_uuid}EntityTopDisplayPlayer] ~onAttack
- Action[a=EntityTopDisplayAnimal;mark={target_uuid}EntityTopDisplayAnimal] ~onCrit
- Action[mark={target_uuid}EntityTopDisplayPlayer;stop=true] ~onDeath

#血量低於設定量顯示標題和聲音
#If the blood volume is lower than the set volume, the title and sound are displayed.
- Action[a=TitleHealthDisplay] ~onJoin

#持續顯示動態欄
#The dynamic bar is continuously displayed.
- Action[a=ActionBarDisplay;mark=%player_name%ActionBarDisplay] ~onJoin
- Action[mark=%player_name%ActionBarDisplay;stop=true] ~onQuiz

#攻擊顯示BossBar
#The attack shows BossBar.
- Action[a=BoosBarDisplay;mark=%player_name%BoosBarDisplay] ~onAttack
- Action[mark=%player_name%BoosBarDisplay;stop=true] ~onDeath

#被攻擊顯示標題
#The title is displayed when attacked.
- Action[a=TitleDisplayAttacked] ~onDamaged

#移除攻擊顯示的愛心效果.
#Removed the love effect displayed by the attack.
- Action[a=Particle-Remove;mark=%player_name%] ~onJoin

#顯示攻擊出現的效果ID.
#Display the effect ID of the attack.
#- Action[a=Particle-Show;mark=%player_name%] ~onAttack