Action:
#攻擊顯示傷害(向上)
#Attack display damage (up)
- Action[a=AttackDisplayUp] ~onAttack

#攻擊顯示傷害(拋出)
#Attack display damage (throw)
#- Action[a=AttackDisplayThrow] ~onAttack

#攻擊怪物顯示血量
#Attacking monsters shows blood volume.
#實體類型可以到Character/System/EntityType.yml自行增加
#The entity type can be added to Character/System/EntityType.yml.
- Action[a=EntityTopDisplayMonster;mark=target;entityType=Monster] ~onAttack

#攻擊動物顯示血量
#Attack animals show blood volume.
- Action[a=EntityTopDisplayAnimal;mark=target;entityType=Animal] ~onAttack

#攻擊玩家顯示資訊
#The attacking player displays information.
- Action[a=EntityTopDisplayPlayer;mark=target;entityType=Player] ~onAttack

#血量低於設定量顯示標題和聲音
#If the blood volume is lower than the set volume, the title and sound are displayed.
- Action[a=TitleHealthDisplay] ~onJoin

#以下還無法使用 #The following is not yet available.

#- Action[a=ActionBarDisplay] ~onTimer=30
#- Action[a=BoosBarDisplay] ~onAttack